nomads_navigation.settings:
  type: config_object
  label: 'Nomads navigation settings'
  mapping:
    filter_tid:
      type: integer
      label: 'Filter term ID'
      nullable: true
    filter_tids:
      type: sequence
      label: 'Filter term IDs'
      sequence:
        type: integer
        label: 'Filter term ID'
    sort_key_tids:
      type: sequence
      label: 'Sort key term IDs'
      sequence:
        type: integer
        label: 'Sort key term ID'
    specific_navigation_parent_tids:
      type: sequence
      label: 'Specific navigation term tokens'
      sequence:
        type: string
        label: 'Specific navigation term token'
    term_label_overrides:
      type: sequence
      label: 'Term label overrides'
      sequence:
        type: label
        label: 'Term label override'
    view_title:
      type: text
      label: 'View title'
    view_subtitle:
      type: text
      label: 'View subtitle'
