<?php

/**
 * Implements hook_form_alter().
 */
function nomads_listing_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
}

/**
 * Implements hook_entity_type_build().
 */
function nomads_listing_entity_type_build(array &$entity_types): void {
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function nomads_listing_menu_local_tasks_alter(array &$data, $route_name, \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability): void {
  if (!isset($data['tabs'][0]['entity.node.delete_form'])) {
    return;
  }

  $data['tabs'][0]['entity.node.delete_form']['#weight'] = 999;
}
