<?php

/**
 * @file
 * Install file for field_toggler.
 */

/**
 * Implements hook_schema().
 */
function field_toggler_schema() {
  $schema['field_toggler_state'] = [
    'description' => 'Stores per field toggle state for entities.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
      ],
      'entity_type' => [
        'type' => 'varchar',
        'length' => 64,
        'not null' => TRUE,
      ],
      'bundle' => [
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
      ],
      'entity_id' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'field_name' => [
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
      ],
      'langcode' => [
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
      ],
      'delta' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'is_on' => [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['id'],
    'indexes' => [
      'field_toggler_lookup' => ['entity_type', 'entity_id', 'field_name', 'langcode', 'delta'],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function field_toggler_uninstall() {
  \Drupal::database()->schema()->dropTable('field_toggler_state');
}
