paragraphs.paragraphs_type.*.third_party.paragraph_relevance:
  type: mapping
  label: 'Paragraph relevance settings'
  mapping:
    css_classes:
      type: string
      label: 'CSS Classes'

field.field.*.*.third_party.paragraph_relevance:
  type: mapping
  label: 'Paragraph relevance field settings'
  mapping:
    open_default:
      type: boolean
      label: 'Open empty paragraph by default'

field.formatter.settings.paragraph_relevance_rendered_relevant_paragraph:
  type: mapping
  label: 'Rendered relevant paragraph formatter settings'
  mapping:
    view_mode:
      type: string
      label: 'View mode'
    link:
      type: boolean
      label: 'Show links'
    relevance_values:
      type: sequence
      label: 'Relevance values'
      sequence:
        type: string
        label: 'Relevance value'
